Repository wahanegi/clever-calculator, pull requests merged in 2025-01, with the labels that each got.

#2 PC-10: Set Up RuboCop
  .gitignore
  .rubocop.yml
  Gemfile
  Gemfile.lock
Labels: safe to merge w/o testing, review done

#4 PC-23 Select and Add starting gems
  Gemfile
  Gemfile.lock
Labels: safe to merge w/o testing, review done

#3 [PC-15] Add README to the project
  README.md
Labels: review needed

#5 PC-17: Create User model using devise gem
  .rspec
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/models/user.rb
  app/views/home/app.html.erb
  app/views/layouts/application.html.erb
  config/environments/development.rb
  config/environments/test.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20250114090731_devise_create_users.rb
  db/schema.rb
  spec/factories/users.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/support/factory_bot.rb
Labels: review done

#7 PC-19 Add ActiveAdmin gem
  Gemfile
  Gemfile.lock
  app/admin/admin_users.rb
  app/admin/dashboard.rb
  app/admin/users.rb
  app/assets/config/manifest.js
  app/assets/javascripts/active_admin.js
  app/assets/stylesheets/active_admin.scss
  app/assets/stylesheets/application.bootstrap.scss
  app/models/admin_user.rb
  app/models/user.rb
  app/views/layouts/application.html.erb
  config/initializers/active_admin.rb
  config/initializers/assets.rb
  config/routes.rb
  db/migrate/20250116165333_devise_create_admin_users.rb
  db/migrate/20250116165334_create_active_admin_comments.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/admin_users.rb
Labels: review done

#8 PC-22: Create Customer model
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/admin/admin_users.rb
  app/admin/customers.rb
  app/admin/dashboard.rb
  app/assets/config/manifest.js
  app/assets/javascripts/active_admin.js
  app/assets/stylesheets/active_admin.scss
  app/models/admin_user.rb
  app/models/customer.rb
  app/views/layouts/application.html.erb
  config/initializers/active_admin.rb
  config/routes.rb
  db/migrate/20250116103055_create_customers.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/customers.rb
  spec/models/customer_spec.rb
Labels: safe to merge w/o testing, review done
