Repository wahanegi/clever-calculator, pull requests merged in 2025-03, with the labels that each got.

#46 PC-67: AdminUsers management in ActiveAdmin
  app/admin/admin_users.rb
  app/models/admin_user.rb
  db/migrate/20250318094556_add_trackable_to_admin_users.rb
  db/schema.rb
  spec/requests/admin/admin_users_controller_spec.rb
Labels: qa done, review done

#47 PC-70: Improve filter item consistency in Active Admin
  app/assets/stylesheets/active_admin.scss
  app/assets/stylesheets/active_admin/forms/_select.scss
Labels: qa done, review done

#38 PC-59: Navigation Setup and Multi-Step Process Management
  .env.example
  .prettierrc
  Gemfile
  Gemfile.lock
  app/assets/images/box-arrow-right.svg
  app/assets/images/logo.png
  app/assets/images/logo.svg
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/buttons.scss
  app/assets/stylesheets/customer_info.scss
  app/assets/stylesheets/icons.scss
  app/assets/stylesheets/reset.scss
  app/assets/stylesheets/typography.scss
  app/assets/stylesheets/variables.scss
  app/controllers/api/v1/quotes_controller.rb
  app/controllers/application_controller.rb
  app/controllers/home_controller.rb
  app/controllers/homepage_controller.rb
  app/helpers/home_helper.rb
  app/helpers/homepage_helper.rb
  app/javascript/application.js
  app/javascript/components/App.jsx
  app/javascript/components/hooks/index.js
  app/javascript/components/hooks/useAppHooks.js
  app/javascript/components/index.jsx
  app/javascript/components/layout/Layout.jsx
  app/javascript/components/layout/NavbarTop.jsx
  app/javascript/components/layout/index.js
  app/javascript/components/pages/CustomerInfo.jsx
  app/javascript/components/pages/ItemsPricing.jsx
  app/javascript/components/pages/index.js
  app/javascript/components/services/api/axiosInstance.js
  app/javascript/components/services/api/httpRequests.js
  app/javascript/components/services/fetchService.js
  app/javascript/components/services/index.js
  app/javascript/components/shared/constants.js
  app/javascript/components/shared/index.js
  app/javascript/components/store/index.js
  app/javascript/components/ui/PcButton.jsx
  app/javascript/components/ui/index.js
  app/models/customer.rb
  app/models/quote.rb
  app/models/user.rb
  app/serializers/quote_serializer.rb
  app/views/home/app.html.erb
  app/views/homepage/index.html.erb
  app/views/layouts/application.html.erb
  config/routes.rb
  db/migrate/20250311043958_create_quotes.rb
  db/migrate/20250318130056_add_step_to_quotes.rb
  db/schema.rb
  package.json
  spec/factories/quotes.rb
  spec/models/customer_spec.rb
  spec/models/quote_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/requests/api/v1/quotes_spec.rb
  spec/requests/homepage_spec.rb
  yarn.lock
Labels: qa done, review done, requires DB migrations

#50 PC-72: Multiple validation messages are displayed in Active Admin for single issues with the password and email
  app/admin/users.rb
  app/models/user.rb
Labels: qa done, review done

#52 PC-79 Resolving SCSS Compilation Issue: Updating Deprecated Syntax
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/application/buttons.scss
  app/assets/stylesheets/application/customer_info.scss
  app/assets/stylesheets/application/icons.scss
  app/assets/stylesheets/application/reset.scss
  app/assets/stylesheets/application/typography.scss
  app/assets/stylesheets/application/variables.scss
  app/javascript/components/index.jsx
  app/views/homepage/index.html.erb
  package.json
  yarn.lock
Labels: qa done, review done

#49 PC-68: User Authentication and Access Request System
  app/assets/images/eye_hide_icon.svg
  app/assets/images/eye_show_icon.svg
  app/assets/images/login_background.png
  app/assets/images/logo.png
  app/assets/images/logo.svg
  app/assets/images/person.svg
  app/assets/javascripts/password_toggle.js
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/application/login_page.scss
  app/assets/stylesheets/application/reset.scss
  app/assets/stylesheets/application/typography.scss
  app/assets/stylesheets/application/variables.scss
  app/views/devise/sessions/new.html.erb
  config/initializers/assets.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
Labels: qa done, review done

#55 PC-89: Add AWS S3 bucket and place for credentials
  app.json
Labels: review done
